#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          spunkybot
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript for Spunky Bot
# Description:       Start/Stop/Restart the Spunky Bot service daemon
### END INIT INFO

# Installation:
# Move this file to /etc/init.d/spunkybot
# Make it executable: sudo chmod +x /etc/init.d/spunkybot
# Start at boot: sudo update-rc.d spunkybot defaults
# Manual start: sudo /etc/init.d/spunkybot start

# Change the next 3 lines to suit where you installed Spunky Bot, and which user is running the Urban Terror server
DIR=/opt/spunkybot
USER=q3ut4
GROUP=q3ut4

# Don't modify the code below
DAEMON="/usr/bin/python $DIR/spunky.py"
NAME=spunkybot

# Get LSB functions
. /lib/lsb/init-functions

case "$1" in
    start)
        log_begin_msg "Starting service $NAME..."
        umask 002
        if start-stop-daemon --start --quiet --background --chdir $DIR --chuid $USER:$GROUP --exec $DAEMON; then
            log_end_msg 0
        else
            log_end_msg $?
        fi
        ;;

    stop)
        log_begin_msg "Stopping service $NAME..."
        if start-stop-daemon --stop --quiet --oknodo --exec $DAEMON; then
                log_end_msg 0
        else
                log_end_msg $?
        fi
        ;;

    restart)
        log_begin_msg "Restarting service $NAME..."
        start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
        sleep 3
        start-stop-daemon --start --quiet --background --chdir $DIR --chuid $USER:$GROUP --exec $DAEMON
        log_end_msg $?
        ;;

    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
        exit 1
        ;;
esac
exit 0