#!/bin/sh
set -e

case "$1" in
    remove)
        rm -f /opt/spunkybot/*.py[co]
        rm -f /opt/spunkybot/devel.log*
        rm -f /opt/spunkybot/lib/*.py[co]
    ;;
    purge)
        rm -rf /opt/spunkybot
        # remove user
        deluser --system q3ut4
    ;;
    abort-install|failed-upgrade|abort-upgrade)
    ;;
esac

#DEBHELPER#

exit 0
