#!/bin/sh
set -e

case "$1" in
    configure)
        # add user/group
        id -u q3ut4 >/dev/null 2>&1 || adduser --quiet --system --no-create-home --group --home /opt/spunkybot q3ut4
        # change owner
        chown -R q3ut4:q3ut4 /opt/spunkybot
    ;;
    abort-remove|abort-upgrade)
    ;;
esac

#DEBHELPER#

exit 0
